// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfWLiKHerifGp46U6TxpqzKBLG97VXfu0',
    appId: '1:1067279037371:web:a8c53c73c8aa3168dc4a9e',
    messagingSenderId: '1067279037371',
    projectId: 'mut2a-110cc',
    authDomain: 'mut2a-110cc.firebaseapp.com',
    storageBucket: 'mut2a-110cc.firebasestorage.app',
    measurementId: 'G-CLHTM05CZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdOH8IV1psa-zj2YK-Ild46b0kP0qhMfk',
    appId: '1:1067279037371:android:d67f7db8e753b040dc4a9e',
    messagingSenderId: '1067279037371',
    projectId: 'mut2a-110cc',
    storageBucket: 'mut2a-110cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWCWD-0-11Izb9UTPb0fFjV8P73MQdXO4',
    appId: '1:1067279037371:ios:85a06ddb42b0dae5dc4a9e',
    messagingSenderId: '1067279037371',
    projectId: 'mut2a-110cc',
    storageBucket: 'mut2a-110cc.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWCWD-0-11Izb9UTPb0fFjV8P73MQdXO4',
    appId: '1:1067279037371:ios:85a06ddb42b0dae5dc4a9e',
    messagingSenderId: '1067279037371',
    projectId: 'mut2a-110cc',
    storageBucket: 'mut2a-110cc.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfWLiKHerifGp46U6TxpqzKBLG97VXfu0',
    appId: '1:1067279037371:web:a8c53c73c8aa3168dc4a9e',
    messagingSenderId: '1067279037371',
    projectId: 'mut2a-110cc',
    authDomain: 'mut2a-110cc.firebaseapp.com',
    storageBucket: 'mut2a-110cc.firebasestorage.app',
    measurementId: 'G-CLHTM05CZ0',
  );

}