// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmwnBcYFmtTE9dId_AB-VMgigYe48_nU',
    appId: '1:679675096170:web:db3c1570ca5c3a6edb6e13',
    messagingSenderId: '679675096170',
    projectId: 'fir-75e4e',
    authDomain: 'fir-75e4e.firebaseapp.com',
    storageBucket: 'fir-75e4e.firebasestorage.app',
    measurementId: 'G-XNZQG9M1QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3WS7XAGRKUnZTqbFcBbyYCfjNQX5kk_8',
    appId: '1:679675096170:android:c2c513e5e6e3b609db6e13',
    messagingSenderId: '679675096170',
    projectId: 'fir-75e4e',
    storageBucket: 'fir-75e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ZNd7Vtx8Gw2e5iBxSFd_UEdhAlAkAB8',
    appId: '1:679675096170:ios:9456d4ac11180062db6e13',
    messagingSenderId: '679675096170',
    projectId: 'fir-75e4e',
    storageBucket: 'fir-75e4e.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ZNd7Vtx8Gw2e5iBxSFd_UEdhAlAkAB8',
    appId: '1:679675096170:ios:9456d4ac11180062db6e13',
    messagingSenderId: '679675096170',
    projectId: 'fir-75e4e',
    storageBucket: 'fir-75e4e.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfmwnBcYFmtTE9dId_AB-VMgigYe48_nU',
    appId: '1:679675096170:web:10db0c6feab2588ddb6e13',
    messagingSenderId: '679675096170',
    projectId: 'fir-75e4e',
    authDomain: 'fir-75e4e.firebaseapp.com',
    storageBucket: 'fir-75e4e.firebasestorage.app',
    measurementId: 'G-ZGN3E5E544',
  );
}
